language: python

python:
  - "3.6"

cache: pip
install: 
  - pip install -r requirements.txt
  - pip install coveralls

script: 
  - pytest--cov=api
  - coverage
  - coveralls 
  
after_success:
  - coveralls
  