anguage: python

python:
  - "3.6"

cache: pip
install: 
  - pip install -r requirements.txt
  - pip install coveralls

script: 
  - pytest -v --cov api --cov-report term-missing
  - coverage report
  
after_success:
  - coveralls