language: python

python:
  - "3.6"

cache: pip
install: 
  - pip install -r requirements.txt
  - pip install coveralls

script: 
  - py.test --cov-report term-missing --cov api -v
  - coverage
  - coveralls 
  
after_success:
  - coveralls
  