language: python

python:
  - "3.6"

cache: pip
install: 
  - pip install -r requirements.txt
  - pip install coveralls

script: 
  - python3 -m pytest --cov=api tests/
  - coverage
  - coveralls 
  
after_success:
  - coveralls
  